name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey nice to see you! Thank you for rasising this issue, this will be reviewed by admins."
        pr-message: "Hey nice to see you! Thank you for making this PR. All PR's are very valuable to us and this will be reviewed by admins and adjusted if needed."
